name: Actualizar canciones populares

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install node-fetch@2 @octokit/rest
      - name: Ejecutar script para actualizar canciones
        run: node updateTopSongs.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
